Tutorials
e3modelling/OPEN-PROM pull request #14
Opened 2023-10-09 10:34 UTC by Redmonkeycloud

New Folder containing all the tutorials from wiki.

2023-10-09 10:44 UTC, derevirn commented
Rename the `Home.md` file to `README.md` so it is displayed automatically in the tutorials folder. Also, replace any references to Wiki with Tutorial.

2023-10-09 10:51 UTC, giannou requested changes
better have a sense of flow: numbered file names would help (see also here: https://github.com/remindmodel/remind/tree/develop/tutorials)

2023-10-09 10:51 UTC, giannou commented on Tutorials/Home.md
> +Welcome to the OPEN-PROM wiki!
this is not a Wiki anymore, suggested change: refer to the Turorials folder rather than the Wiki

2023-10-09 10:53 UTC, Redmonkeycloud commented
Derevirn's suggestions have been integrated!

2023-10-09 11:21 UTC, derevirn commented
Links between tutorials need to have this format:

[link](https://github.com/e3modelling/OPEN-PROM/blob/main/Tutorials/File.md)

Also, spaces in links must be replaced with %20, or ideally remove them from file names entirely, and put underscores ( _ ) instead.

2023-10-10 07:55 UTC, Redmonkeycloud commented
Anastasis suggestions about numbered file names added!

2023-10-10 10:12 UTC, Redmonkeycloud commented
So all the links have been replaced with file names, the number filling system has been integrated and reworked and last but not least brief descriptions of all the files has been added in the README file.

2023-10-10 11:33 UTC, giannou approved these changes

2023-10-10 11:48 UTC, merged